# Use root/example as user/password credentials
version: '3.1'
services:
  server:
    env_file:
      - .env
    container_name: server
    networks:
      - app-network
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 4001:4001
    stdin_open: true

  mongo:
    env_file:
      - .env
    networks:
      - app-network
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - 27017:27017

  redis:
    env_file:
      - .env
    networks:
      - app-network
    image: redis:latest
    ports:
      - 6379:6379
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT: 6379
      REDIS_DATABASES: 16
    command: /bin/sh -c 'redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}'
    restart: always

networks:
  app-network:
    name: global
    external: true
